# Generated by Django 5.1.6 on 2025-10-15 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0002_alter_customer_branch_alter_customer_province_state_and_more'),
        ('lift', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('type', models.CharField(choices=[('Parts/Peripheral Quotation', 'Parts/Peripheral Quotation'), ('Repair', 'Repair'), ('AMC Renewal Quotation', 'AMC Renewal Quotation'), ('AMC', 'AMC')], default='Parts/Peripheral Quotation', max_length=50, verbose_name='Quotation Type')),
                ('year_of_make', models.CharField(blank=True, max_length=4)),
                ('date', models.DateField(auto_now_add=True)),
                ('remark', models.TextField(blank=True)),
                ('other_remark', models.TextField(blank=True)),
                ('uploads_files', models.FileField(blank=True, null=True, upload_to='quotation_uploads/')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.customer')),
                ('lifts', models.ManyToManyField(blank=True, help_text='Select one or more lifts associated with this quotation', to='lift.lift')),
            ],
            options={
                'verbose_name': 'Quotation',
                'verbose_name_plural': 'Quotations',
            },
        ),
    ]
