# Generated by Django 5.1.6 on 2025-10-16 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quotation', '0001_initial'),
        ('amc', '0004_alter_amc_amcname_alter_amc_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='amc_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='amc.amctype'),
        ),
    ]
