# Generated by Django 5.1.6 on 2025-10-16 09:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quotation', '0002_quotation_amc_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='sales_service_executive',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'employee'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_quotations', to=settings.AUTH_USER_MODEL),
        ),
    ]
