# Generated by Django 5.2.7 on 2025-11-05 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quotation', '0003_quotation_sales_service_executive'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('closed', 'Closed')], default='open', max_length=20, verbose_name='Status'),
        ),
    ]
