# Generated by Django 5.2.7 on 2025-11-07 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quotation', '0004_quotation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='status',
        ),
    ]
