# Generated by Django 5.1.14 on 2025-11-20 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quotation', '0005_remove_quotation_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkImportQuotation',
            fields=[
            ],
            options={
                'verbose_name': 'Bulk Import',
                'verbose_name_plural': 'Bulk Import',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Quotation.quotation',),
        ),
    ]
