# Generated by Django 5.1.14 on 2025-12-15 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quotation', '0006_bulkimportquotation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='sales_service_executive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_quotations', to=settings.AUTH_USER_MODEL),
        ),
    ]
