# Generated by Django 5.2.7 on 2025-10-26 11:28

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0011_alter_customer_generate_license_now'),
        ('items', '0003_alter_item_item_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceOfSupply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryChallan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('date', models.DateField()),
                ('reference_number', models.CharField(blank=True, max_length=50, null=True)),
                ('challan_type', models.CharField(choices=[('Supply of Liquid Gas', 'Supply of Liquid Gas'), ('Goods Supply', 'Goods Supply'), ('Service Delivery', 'Service Delivery'), ('Other', 'Other')], default='Supply of Liquid Gas', max_length=50)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('discount_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('adjustment', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('customer_note', models.TextField(blank=True)),
                ('terms_conditions', models.TextField(blank=True)),
                ('uploads_files', models.FileField(blank=True, null=True, upload_to='delivery_challan_uploads/')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.customer')),
                ('place_of_supply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.placeofsupply')),
            ],
            options={
                'verbose_name': 'Delivery Challan',
                'verbose_name_plural': 'Delivery Challans',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryChallanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('qty', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('challan', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='delivery.deliverychallan')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.item')),
            ],
        ),
    ]
