# Generated by Django 5.2.7 on 2025-11-07 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_customerfollowup'),
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverychallan',
            name='customer',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, to='customer.customer'),
            preserve_default=False,
        ),
    ]
