# Generated by Django 5.1.14 on 2025-11-16 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_alter_deliverychallan_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverychallan',
            name='adjustment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='deliverychallan',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='deliverychallanitem',
            name='qty',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='deliverychallanitem',
            name='rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='deliverychallanitem',
            name='total',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=20),
        ),
    ]
