# Generated by Django 5.1.14 on 2025-11-20 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_alter_deliverychallan_adjustment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkImportDeliveryChallan',
            fields=[
            ],
            options={
                'verbose_name': 'Bulk Import',
                'verbose_name_plural': 'Bulk Import',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('delivery.deliverychallan',),
        ),
    ]
