# Generated by Django 5.2.7 on 2025-10-25 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Requisition', '0002_requisition_employee'),
        ('items', '0003_alter_item_item_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_no', models.CharField(editable=False, max_length=10, unique=True)),
                ('date', models.DateField()),
                ('description', models.TextField(blank=True, null=True)),
                ('transaction_type', models.CharField(choices=[('INWARD', 'Inward'), ('OUTWARD', 'Outward')], max_length=10)),
                ('inward_qty', models.PositiveIntegerField(default=0, help_text='Quantity received/added to stock')),
                ('outward_qty', models.PositiveIntegerField(default=0, help_text='Quantity issued/removed from stock')),
                ('unit_value', models.DecimalField(decimal_places=2, default=0.0, help_text='Value per unit', max_digits=10)),
                ('total_value', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=12)),
                ('reference', models.CharField(blank=True, help_text='Reference document number', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_entries', to='items.item')),
            ],
            options={
                'verbose_name': 'Stock Register',
                'verbose_name_plural': 'Stock Register',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
