# Generated by Django 5.1.14 on 2025-11-20 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Requisition', '0003_stockregister'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkImportRequisition',
            fields=[
            ],
            options={
                'verbose_name': 'Bulk Import',
                'verbose_name_plural': 'Bulk Import',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Requisition.requisition',),
        ),
    ]
