# Generated by Django 5.1.6 on 2025-10-15 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.branch'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='province_state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.provincestate'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='routes',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.route'),
        ),
    ]
