# Generated by Django 5.1.6 on 2025-10-16 03:36

import customer.models
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_customer_billing_name_alter_customer_branch_and_more'),
        ('lift', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_no', models.CharField(editable=False, max_length=50, unique=True)),
                ('period_start', models.DateField(default=datetime.date.today)),
                ('period_end', models.DateField(default=customer.models.one_year_from_today)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='license_attachments/')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='customer.customer')),
                ('lift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='lift.lift')),
            ],
        ),
    ]
