# Generated by Django 5.1.6 on 2025-10-16 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_customerlicense'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerlicense',
            name='attachment',
        ),
    ]
