# Generated by Django 5.1.6 on 2025-10-16 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_remove_customerlicense_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='generate_license_now',
            field=models.BooleanField(default=False),
        ),
    ]
