# Generated by Django 5.1.6 on 2025-10-17 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_customer_same_as_site_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='same_as_site_address',
        ),
    ]
