# Generated by Django 5.1.6 on 2025-10-17 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0008_remove_customer_same_as_site_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='same_as_site_address',
            field=models.BooleanField(default=False, help_text='Check to set office address same as site address'),
        ),
    ]
