# Generated by Django 5.1.6 on 2025-10-17 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0009_customer_same_as_site_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='generate_license_now',
            field=models.BooleanField(default=False, help_text='Tick this to auto-generate a license if lift job number matches.'),
        ),
    ]
