# Generated by Django 5.1.6 on 2025-10-17 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_alter_customer_generate_license_now'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='generate_license_now',
            field=models.BooleanField(default=False),
        ),
    ]
