# Generated by Django 5.2.7 on 2025-11-04 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_customercontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='notes',
            field=models.TextField(blank=True, help_text='Additional notes for this customer', null=True),
        ),
    ]
