# Generated by Django 5.2.7 on 2025-11-04 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0013_customer_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('rating', models.IntegerField(default=0, help_text='Rating out of 5 stars')),
                ('friendliness', models.CharField(blank=True, choices=[('very_satisfied', 'Very Satisfied'), ('satisfied', 'Satisfied'), ('neutral', 'Neutral'), ('unsatisfied', 'Unsatisfied'), ('very_unsatisfied', 'Very Unsatisfied')], max_length=20, null=True)),
                ('knowledge', models.CharField(blank=True, choices=[('very_satisfied', 'Very Satisfied'), ('satisfied', 'Satisfied'), ('neutral', 'Neutral'), ('unsatisfied', 'Unsatisfied'), ('very_unsatisfied', 'Very Unsatisfied')], max_length=20, null=True)),
                ('quickness', models.CharField(blank=True, choices=[('very_satisfied', 'Very Satisfied'), ('satisfied', 'Satisfied'), ('neutral', 'Neutral'), ('unsatisfied', 'Unsatisfied'), ('very_unsatisfied', 'Very Unsatisfied')], max_length=20, null=True)),
                ('review', models.TextField(blank=True, help_text='Review/comment', null=True)),
                ('improvement_suggestion', models.TextField(blank=True, help_text='How can we improve our service?', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='customer.customer')),
            ],
            options={
                'verbose_name': 'Customer Feedback',
                'verbose_name_plural': 'Customer Feedbacks',
                'ordering': ['-created_date'],
            },
        ),
    ]
