# Generated by Django 5.2.7 on 2025-11-04 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_customerfeedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followup_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('follow_up_date', models.DateField(help_text='Date for the follow-up')),
                ('comment', models.TextField(blank=True, help_text='Comment/notes for the follow-up', null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(blank=True, help_text='Contact person for this follow-up', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_ups', to='customer.customercontact')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='customer.customer')),
            ],
            options={
                'verbose_name': 'Customer Follow-Up',
                'verbose_name_plural': 'Customer Follow-Ups',
                'ordering': ['-follow_up_date', '-created_date'],
            },
        ),
    ]
