# Generated by Django 5.1.14 on 2025-11-13 14:42

import django.db.models.deletion
from django.db import migrations, models


def migrate_city_data(apps, schema_editor):
    """Migrate existing city string values to City objects"""
    Customer = apps.get_model('customer', 'Customer')
    City = apps.get_model('customer', 'City')
    
    # Get all unique city values from existing customers
    customers = Customer.objects.exclude(city_old__isnull=True).exclude(city_old='')
    city_values = set()
    for customer in customers:
        if customer.city_old:
            city_values.add(customer.city_old.strip())
    
    # Create City objects for each unique city value
    city_map = {}
    for city_value in city_values:
        if city_value:  # Skip empty strings
            city, created = City.objects.get_or_create(value=city_value)
            city_map[city_value] = city
    
    # Update customers to reference City objects
    for customer in customers:
        if customer.city_old and customer.city_old.strip() in city_map:
            customer.city = city_map[customer.city_old.strip()]
            customer.save()


def reverse_migrate_city_data(apps, schema_editor):
    """Reverse migration: copy city values back to city_old field"""
    Customer = apps.get_model('customer', 'Customer')
    
    for customer in Customer.objects.exclude(city__isnull=True):
        if customer.city:
            customer.city_old = customer.city.value
            customer.save()


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_customerfollowup'),
    ]

    operations = [
        # Step 1: Create City model
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, unique=True)),
            ],
        ),
        # Step 2: Rename existing city field to city_old (temporary)
        migrations.RenameField(
            model_name='customer',
            old_name='city',
            new_name='city_old',
        ),
        # Step 3: Add new ForeignKey field (nullable)
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.city'),
        ),
        # Step 4: Migrate data from city_old to city
        migrations.RunPython(migrate_city_data, reverse_migrate_city_data),
        # Step 5: Remove the old city_old field
        migrations.RemoveField(
            model_name='customer',
            name='city_old',
        ),
    ]
