# Generated by Django 5.1.14 on 2025-11-13 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0016_city_alter_customer_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Latitude coordinate (-90 to 90). Used for mapping and location services.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Longitude coordinate (-180 to 180). Used for mapping and location services.', max_digits=11, null=True),
        ),
    ]
