# Generated by Django 5.1.14 on 2025-11-13 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0017_customer_latitude_customer_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='site_id',
        ),
    ]
