# Generated by Django 5.1.14 on 2025-11-14 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0018_remove_customer_site_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='contact_person_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='province_state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.provincestate'),
        ),
    ]
