# Generated by Django 5.1.14 on 2025-11-20 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0019_make_contact_person_name_and_province_state_optional'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkImportCustomer',
            fields=[
            ],
            options={
                'verbose_name': 'Bulk Import',
                'verbose_name_plural': 'Bulk Import',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('customer.customer',),
        ),
        migrations.AddField(
            model_name='customer',
            name='generate_customer_license_page',
            field=models.BooleanField(default=False, help_text='Check to generate custom page for customer license'),
        ),
    ]
