# Generated by Django 5.1.14 on 2025-11-20 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0020_bulkimportcustomer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerlicense',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired')], default='active', help_text='License status', max_length=20),
        ),
        migrations.AlterField(
            model_name='customerlicense',
            name='license_no',
            field=models.CharField(help_text='License reference number (auto-generated if left blank)', max_length=50, unique=True),
        ),
    ]
