# Generated by Django 5.1.14 on 2025-11-20 04:06

from django.db import migrations, models


def populate_license_ref_no(apps, schema_editor):
    """Populate license_ref_no for existing records"""
    CustomerLicense = apps.get_model('customer', 'CustomerLicense')
    for idx, license_obj in enumerate(CustomerLicense.objects.all().order_by('id'), start=1):
        license_obj.license_ref_no = f"LIC{idx:04d}"
        license_obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0021_customerlicense_status_and_more'),
    ]

    operations = [
        # Step 1: Add license_ref_no as nullable first (no unique constraint yet)
        migrations.AddField(
            model_name='customerlicense',
            name='license_ref_no',
            field=models.CharField(blank=True, editable=False, help_text='License reference number (auto-generated)', max_length=50, null=True),
        ),
        # Step 2: Populate license_ref_no for existing records
        migrations.RunPython(populate_license_ref_no, migrations.RunPython.noop),
        # Step 3: Make license_ref_no non-nullable and unique
        migrations.AlterField(
            model_name='customerlicense',
            name='license_ref_no',
            field=models.CharField(editable=False, help_text='License reference number (auto-generated)', max_length=50, unique=True),
        ),
        # Step 4: Alter license_no to be for government license (nullable, unique)
        migrations.AlterField(
            model_name='customerlicense',
            name='license_no',
            field=models.CharField(blank=True, help_text='Government-issued license number (manually entered)', max_length=100, null=True, unique=True),
        ),
    ]
