# Generated by Django 5.1.14 on 2025-12-16 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0022_customerlicense_license_ref_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp_code', models.CharField(max_length=6)),
                ('email', models.EmailField(max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('attempts', models.IntegerField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='otps', to='customer.customer')),
            ],
            options={
                'verbose_name': 'Customer OTP',
                'verbose_name_plural': 'Customer OTPs',
                'ordering': ['-created_at'],
            },
        ),
    ]
