# Generated by Django 5.1.6 on 2025-10-16 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lift', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lift',
            name='load_kg',
            field=models.PositiveIntegerField(blank=True, help_text='Automatically calculated as passengers × 68 if left empty, but editable.', null=True),
        ),
        migrations.AlterField(
            model_name='lift',
            name='no_of_passengers',
            field=models.PositiveIntegerField(),
        ),
    ]
