# Generated by Django 5.1.6 on 2025-10-17 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lift', '0002_alter_lift_load_kg_alter_lift_no_of_passengers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lift',
            name='load_kg',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
