# Generated by Django 5.1.6 on 2025-10-19 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lift', '0003_alter_lift_load_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='lift',
            name='reference_id',
            field=models.CharField(editable=False, max_length=20, unique=True, null=True),
        ),
        migrations.AlterField(
            model_name='lift',
            name='lift_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
