# Generated by Django 5.1.6 on 2025-10-19 10:39

from django.db import migrations
import datetime


def populate_reference_ids(apps, schema_editor):
    """Populate reference_id for existing Lift records"""
    Lift = apps.get_model('lift', 'Lift')

    # Get all lifts without reference_id
    lifts_without_ref = Lift.objects.filter(reference_id__isnull=True)

    for lift in lifts_without_ref:
        # Generate reference ID in format: LIFT-YYYY-NNNN
        year = datetime.datetime.now().year
        # Get the count of lifts created this year and add 1
        count = Lift.objects.filter(
            reference_id__startswith=f'LIFT-{year}-'
        ).count() + 1
        lift.reference_id = f'LIFT-{year}-{count:04d}'
        lift.save(update_fields=['reference_id'])


def reverse_populate_reference_ids(apps, schema_editor):
    """Reverse migration - clear reference_id values"""
    Lift = apps.get_model('lift', 'Lift')
    Lift.objects.filter(reference_id__isnull=False).update(reference_id=None)


class Migration(migrations.Migration):

    dependencies = [
        ('lift', '0004_lift_reference_id_alter_lift_lift_code'),
    ]

    operations = [
        migrations.RunPython(
            populate_reference_ids,
            reverse_populate_reference_ids
        ),
    ]
