# Generated by Django 5.1.6 on 2025-10-19 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lift', '0005_populate_reference_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lift',
            name='reference_id',
            field=models.CharField(default=2, editable=False, max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
