# Generated by Django 5.2.7 on 2025-11-03 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lift', '0006_alter_lift_reference_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lift',
            name='license_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
