# Generated by Django 5.1.14 on 2025-11-20 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lift', '0007_alter_lift_license_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkImportLift',
            fields=[
            ],
            options={
                'verbose_name': 'Bulk Import',
                'verbose_name_plural': 'Bulk Import',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('lift.lift',),
        ),
    ]
