# Generated by Django 5.2.9 on 2025-12-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lift', '0008_bulkimportlift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lift',
            name='lift_code',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
