# Generated by Django 5.1.6 on 2025-10-15 13:46

import django.db.models.deletion
import modelcluster.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0002_alter_customer_branch_alter_customer_province_state_and_more'),
        ('items', '0003_alter_item_item_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('profile_name', models.CharField(max_length=100)),
                ('order_number', models.CharField(blank=True, max_length=50)),
                ('repeat_every', models.CharField(choices=[('week', 'Week'), ('2week', '2 Weeks'), ('month', 'Month'), ('2month', '2 Months'), ('3month', '3 Months'), ('6month', '6 Months'), ('year', 'Year'), ('2year', '2 Years')], default='month', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('last_generated_date', models.DateField(blank=True, null=True)),
                ('billing_address', models.TextField(blank=True)),
                ('gst_treatment', models.CharField(blank=True, max_length=50)),
                ('uploads_files', models.FileField(blank=True, null=True, upload_to='recurring_invoice_uploads/')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='active', max_length=20)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RecurringInvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('qty', models.IntegerField(default=1)),
                ('tax', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.item')),
                ('recurring_invoice', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='recurringInvoice.recurringinvoice')),
            ],
        ),
    ]
