# Generated by Django 5.2.7 on 2025-10-31 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recurringInvoice', '0002_recurringinvoice_sales_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringinvoice',
            name='auto_repeat',
            field=models.BooleanField(default=True, help_text='Enable automatic invoice generation based on repeat_every schedule'),
        ),
    ]
