# Generated by Django 5.1.14 on 2025-11-18 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Routine_services', '0002_allroutineservicespage_lastmonthcompletedpage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutineServiceAll',
            fields=[
            ],
            options={
                'verbose_name': 'All Routine Service',
                'verbose_name_plural': 'All Routine Services',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Routine_services.routineservice',),
        ),
        migrations.CreateModel(
            name='RoutineServiceLastMonthCompleted',
            fields=[
            ],
            options={
                'verbose_name': 'Last Month Completed Routine Service',
                'verbose_name_plural': 'Last Month Completed Routine Services',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Routine_services.routineservice',),
        ),
        migrations.CreateModel(
            name='RoutineServiceLastMonthExpiring',
            fields=[
            ],
            options={
                'verbose_name': 'Last Month Expired Routine Service',
                'verbose_name_plural': 'Last Month Expired Routine Services',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Routine_services.routineservice',),
        ),
        migrations.CreateModel(
            name='RoutineServiceLastMonthOverdue',
            fields=[
            ],
            options={
                'verbose_name': 'Last Month Overdue Routine Service',
                'verbose_name_plural': 'Last Month Overdue Routine Services',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Routine_services.routineservice',),
        ),
        migrations.CreateModel(
            name='RoutineServicePending',
            fields=[
            ],
            options={
                'verbose_name': 'Pending Routine Service',
                'verbose_name_plural': 'Pending Routine Services',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Routine_services.routineservice',),
        ),
        migrations.CreateModel(
            name='RoutineServiceRouteWise',
            fields=[
            ],
            options={
                'verbose_name': 'Route Wise Routine Service',
                'verbose_name_plural': 'Route Wise Routine Services',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Routine_services.routineservice',),
        ),
        migrations.CreateModel(
            name='RoutineServiceThisMonth',
            fields=[
            ],
            options={
                'verbose_name': 'This Month Routine Service',
                'verbose_name_plural': 'This Month Routine Services',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Routine_services.routineservice',),
        ),
        migrations.CreateModel(
            name='RoutineServiceThisMonthCompleted',
            fields=[
            ],
            options={
                'verbose_name': 'This Month Completed Routine Service',
                'verbose_name_plural': 'This Month Completed Routine Services',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Routine_services.routineservice',),
        ),
        migrations.CreateModel(
            name='RoutineServiceThisMonthExpiring',
            fields=[
            ],
            options={
                'verbose_name': 'This Month Expiring Routine Service',
                'verbose_name_plural': 'This Month Expiring Routine Services',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Routine_services.routineservice',),
        ),
        migrations.CreateModel(
            name='RoutineServiceThisMonthOverdue',
            fields=[
            ],
            options={
                'verbose_name': 'This Month Overdue Routine Service',
                'verbose_name_plural': 'This Month Overdue Routine Services',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Routine_services.routineservice',),
        ),
        migrations.CreateModel(
            name='RoutineServiceToday',
            fields=[
            ],
            options={
                'verbose_name': "Today's Routine Service",
                'verbose_name_plural': "Today's Routine Services",
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Routine_services.routineservice',),
        ),
    ]
