# Generated by Django 5.1.6 on 2025-10-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_item_item_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_number',
            field=models.CharField(editable=False, max_length=10, unique=True),
        ),
    ]
