# Generated by Django 5.2.7 on 2025-10-26 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_item_item_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
