# Generated by Django 5.2.7 on 2025-11-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_item_purchase_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='threshold_qty',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
