# Generated by Django 5.1.14 on 2025-11-20 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_alter_item_purchase_price_alter_item_threshold_qty'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkImportItem',
            fields=[
            ],
            options={
                'verbose_name': 'Bulk Import',
                'verbose_name_plural': 'Bulk Import',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('items.item',),
        ),
    ]
