# Generated by Django 5.2.7 on 2025-10-20 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0002_delete_reportaccess'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportPermissions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('view_report_complaints', 'Can view Complaints Report'), ('view_report_invoices', 'Can view Invoices Report'), ('view_report_payments', 'Can view Payments Report'), ('view_report_quotations', 'Can view Quotations Report'), ('view_report_routine_services', 'Can view Routine Service Report'), ('view_report_amc', 'Can view AMC Report')),
                'default_permissions': (),
            },
        ),
    ]
