# Generated by Django 5.1.6 on 2025-10-16 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(editable=False, max_length=50),
        ),
    ]
