# Generated by Django 5.2.7 on 2025-10-24 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_otp'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OTP',
        ),
    ]
