# Generated by Django 5.1.14 on 2025-12-18 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0023_customerotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCustomer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Full name of the sub-customer', max_length=200)),
                ('email', models.EmailField(help_text='Email address of the sub-customer', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Phone number of the sub-customer', max_length=15, null=True)),
                ('can_access_app', models.BooleanField(default=False, help_text="If checked, this sub-customer can access the user app with the customer's credentials")),
                ('is_active', models.BooleanField(default=True, help_text='Whether this sub-customer is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, help_text='Email of the customer who created this sub-customer', max_length=200, null=True)),
                ('customer', models.ForeignKey(help_text='The parent customer who owns this sub-customer', on_delete=django.db.models.deletion.CASCADE, related_name='subcustomers', to='customer.customer')),
            ],
            options={
                'verbose_name': 'Sub Customer',
                'verbose_name_plural': 'Sub Customers',
                'ordering': ['-created_at'],
                'unique_together': {('customer', 'email')},
            },
        ),
    ]
