# Generated by Django 5.2.7 on 2025-10-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='complaint_templates',
            field=models.TextField(blank=True, help_text='Selected complaint templates (comma-separated)', null=True),
        ),
        migrations.AddField(
            model_name='complaint',
            name='lift_info',
            field=models.CharField(blank=True, help_text='Selected lift information', max_length=200, null=True),
        ),
    ]
