# Generated by Django 5.2.7 on 2025-10-28 09:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_complaintassignmenthistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplaintCallUpdateHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_update_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('solution_templates', models.TextField(blank=True, help_text='Selected solution templates (comma-separated)', null=True)),
                ('additional_notes', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('attend_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_updates_made', to=settings.AUTH_USER_MODEL)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='call_update_history', to='complaints.complaint')),
            ],
            options={
                'ordering': ['-call_update_date', '-id'],
            },
        ),
    ]
