# Generated by Django 5.2.7 on 2025-10-28 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0006_complaintstatushistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='customer_signature',
            field=models.ImageField(blank=True, help_text='Customer signature image', null=True, upload_to='complaint_signatures/customer/'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='technician_signature',
            field=models.ImageField(blank=True, help_text='Technician signature image', null=True, upload_to='complaint_signatures/technician/'),
        ),
    ]
