# Generated by Django 5.2.7 on 2025-10-28 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0007_complaint_customer_signature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='customer_signature',
            field=models.TextField(blank=True, help_text='Customer signature text', null=True),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='technician_signature',
            field=models.TextField(blank=True, help_text='Technician signature text', null=True),
        ),
    ]
