# Generated by Django 5.2.3 on 2025-10-31 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("complaints", "0008_alter_complaint_customer_signature_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="complaint",
            name="customer_signature",
            field=models.ImageField(
                blank=True, help_text="Customer signature text", null=True, upload_to=""
            ),
        ),
        migrations.AlterField(
            model_name="complaint",
            name="technician_signature",
            field=models.ImageField(
                blank=True,
                help_text="Technician signature text",
                null=True,
                upload_to="",
            ),
        ),
    ]
