# Generated by Django 5.2.7 on 2025-11-02 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0009_alter_complaint_customer_signature_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='customer_signature',
            field=models.ImageField(blank=True, help_text='Customer signature image', null=True, upload_to='complaints/signatures/'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='technician_signature',
            field=models.ImageField(blank=True, help_text='Technician signature image', null=True, upload_to='complaints/signatures/'),
        ),
    ]
