# Generated by Django 5.1.14 on 2025-11-20 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0010_alter_complaint_customer_signature_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkImportComplaint',
            fields=[
            ],
            options={
                'verbose_name': 'Bulk Import',
                'verbose_name_plural': 'Bulk Import',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('complaints.complaint',),
        ),
    ]
