# Generated by Django 5.1.14 on 2025-12-15 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0011_bulkimportcomplaint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintpriority',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
