# Generated by Django 5.1.14 on 2026-01-06 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0009_bulkimportamc'),
        ('services_shedule', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ServiceSchedule',
        ),
        migrations.CreateModel(
            name='RoutineServiceScheduleView',
            fields=[
            ],
            options={
                'verbose_name': 'Routine Service Schedule',
                'verbose_name_plural': 'Routine Service Schedules',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('amc.amc',),
        ),
    ]
