# Generated by Django 5.1.6 on 2025-10-15 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0002_alter_customer_branch_alter_customer_province_state_and_more'),
        ('items', '0003_alter_item_item_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='AMCType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'AMC Type',
                'verbose_name_plural': 'AMC Types',
            },
        ),
        migrations.CreateModel(
            name='PaymentTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Payment Term',
                'verbose_name_plural': 'Payment Terms',
            },
        ),
        migrations.CreateModel(
            name='AMC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('amcname', models.CharField(blank=True, max_length=100, verbose_name='AMC Pack Name')),
                ('invoice_frequency', models.CharField(choices=[('annually', 'Annually'), ('semi_annually', 'Semi Annually'), ('quarterly', 'Quarterly'), ('monthly', 'Monthly'), ('per_service', 'Per Service')], default='annually', max_length=20, verbose_name='Invoice Frequency')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('equipment_no', models.CharField(blank=True, max_length=50, null=True, verbose_name='Equipment No')),
                ('latitude', models.CharField(blank=True, max_length=255, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_generate_contract', models.BooleanField(default=False, verbose_name='Generate Contract Now')),
                ('no_of_services', models.IntegerField(blank=True, default=12, null=True, verbose_name='No of Services')),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('no_of_lifts', models.IntegerField(blank=True, default=0, null=True, verbose_name='No of Lifts')),
                ('gst_percentage', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True, verbose_name='% GST')),
                ('total_amount_paid', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Total Amount Paid')),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0.0, editable=False, max_digits=10, null=True, verbose_name='Total Value (Incl. GST)')),
                ('contract_amount', models.DecimalField(blank=True, decimal_places=2, default=0.0, editable=False, max_digits=10, null=True)),
                ('amount_due', models.DecimalField(blank=True, decimal_places=2, default=0.0, editable=False, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('on_hold', 'On Hold')], default='active', editable=False, max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('amc_service_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.item', verbose_name='AMC Service Item')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer', verbose_name='Customer Name')),
                ('amc_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='amc.amctype', verbose_name='AMC Type')),
                ('payment_terms', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='amc.paymentterms', verbose_name='Payment Terms')),
            ],
        ),
    ]
