# Generated by Django 5.1.6 on 2025-10-15 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0001_initial'),
        ('customer', '0002_alter_customer_branch_alter_customer_province_state_and_more'),
        ('items', '0003_alter_item_item_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='amctype',
            options={},
        ),
        migrations.AlterModelOptions(
            name='paymentterms',
            options={},
        ),
        migrations.AlterField(
            model_name='amc',
            name='amc_service_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.item'),
        ),
        migrations.AlterField(
            model_name='amc',
            name='amc_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='amc.amctype'),
        ),
        migrations.AlterField(
            model_name='amc',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
        migrations.AlterField(
            model_name='amc',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='amc',
            name='equipment_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='amc',
            name='gst_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='amc',
            name='invoice_frequency',
            field=models.CharField(choices=[('annually', 'Annually'), ('semi_annually', 'Semi Annually'), ('quarterly', 'Quarterly'), ('monthly', 'Monthly'), ('per_service', 'Per Service')], default='annually', max_length=20),
        ),
        migrations.AlterField(
            model_name='amc',
            name='latitude',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Site Address'),
        ),
        migrations.AlterField(
            model_name='amc',
            name='no_of_lifts',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='amc',
            name='no_of_services',
            field=models.IntegerField(blank=True, default=12, null=True),
        ),
        migrations.AlterField(
            model_name='amc',
            name='payment_terms',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='amc.paymentterms'),
        ),
        migrations.AlterField(
            model_name='amc',
            name='start_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='amc',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('on_hold', 'On Hold')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='amc',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, editable=False, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='amc',
            name='total_amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
