# Generated by Django 5.1.6 on 2025-10-15 15:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0002_alter_amctype_options_alter_paymentterms_options_and_more'),
        ('customer', '0003_alter_customer_billing_name_alter_customer_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amc',
            name='amount_due',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='amc',
            name='contract_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='amc',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer', verbose_name='Customer Name'),
        ),
        migrations.AlterField(
            model_name='amc',
            name='equipment_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Job No'),
        ),
        migrations.AlterField(
            model_name='amc',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='amc',
            name='total_amount_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
