# Generated by Django 5.1.6 on 2025-10-15 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0003_alter_amc_amount_due_alter_amc_contract_amount_and_more'),
        ('customer', '0003_alter_customer_billing_name_alter_customer_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='amc',
            name='amcname',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='amc',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer'),
        ),
        migrations.AlterField(
            model_name='amc',
            name='equipment_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='amc',
            name='latitude',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
