# Generated by Django 5.2.7 on 2025-10-20 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0004_alter_amc_amcname_alter_amc_customer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AMCExpiringLastMonth',
            fields=[
            ],
            options={
                'verbose_name': 'Last Month Expired AMC',
                'verbose_name_plural': 'Last Month Expired AMCs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('amc.amc',),
        ),
        migrations.CreateModel(
            name='AMCExpiringNextMonth',
            fields=[
            ],
            options={
                'verbose_name': 'Next Month Expiring AMC',
                'verbose_name_plural': 'Next Month Expiring AMCs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('amc.amc',),
        ),
        migrations.CreateModel(
            name='AMCExpiringThisMonth',
            fields=[
            ],
            options={
                'verbose_name': 'This Month Expiring AMC',
                'verbose_name_plural': 'This Month Expiring AMCs',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('amc.amc',),
        ),
    ]
