# Generated by Django 5.1.14 on 2025-11-13 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0005_amcexpiringlastmonth_amcexpiringnextmonth_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amc',
            name='amcname',
        ),
    ]
