# Generated by Django 5.1.14 on 2025-11-14 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0006_remove_amcname_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='amc',
            name='geo_latitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Latitude coordinate (-90 to 90). Auto-filled from customer.', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='amc',
            name='geo_longitude',
            field=models.DecimalField(blank=True, decimal_places=8, help_text='Longitude coordinate (-180 to 180). Auto-filled from customer.', max_digits=11, null=True),
        ),
        migrations.AlterField(
            model_name='amc',
            name='amc_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='amc.amctype', verbose_name='AMC Pack Type'),
        ),
    ]
