# Generated by Django 5.1.14 on 2025-11-18 06:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0007_add_geo_latitude_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AMCRoutineService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_date', models.DateField()),
                ('block_wing', models.CharField(blank=True, help_text='Block / Wing', max_length=100, null=True)),
                ('status', models.CharField(choices=[('due', 'Due'), ('overdue', 'Overdue'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='due', max_length=20)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='routine_services', to='amc.amc')),
                ('employee_assign', models.ForeignKey(blank=True, help_text='Assigned employee', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_amc_routine_services', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AMC Routine Service',
                'verbose_name_plural': 'AMC Routine Services',
                'ordering': ['service_date'],
            },
        ),
        migrations.CreateModel(
            name='AMCRoutineServiceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_service_date', models.DateField(blank=True, help_text='First service date', null=True)),
                ('frequency_days', models.IntegerField(blank=True, help_text='Frequency in number of days', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amc', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='routine_service_schedule', to='amc.amc')),
            ],
            options={
                'verbose_name': 'AMC Routine Service Schedule',
                'verbose_name_plural': 'AMC Routine Service Schedules',
            },
        ),
    ]
