# Generated by Django 5.1.6 on 2025-10-15 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PaymentReceived', '0001_initial'),
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentreceived',
            name='invoice',
            field=models.ForeignKey(blank=True, help_text='Linked to a specific invoice for deposit consideration', null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoice.invoice'),
        ),
    ]
