# Generated by Django 5.2.7 on 2025-10-31 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaymentReceived', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentreceived',
            name='payment_type',
            field=models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('neft', 'NEFT')], default='cash', max_length=20),
        ),
    ]
