# Generated by Django 5.2.7 on 2025-11-07 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PaymentReceived', '0003_alter_paymentreceived_payment_type'),
        ('customer', '0015_customerfollowup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentreceived',
            name='customer',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='customer.customer'),
            preserve_default=False,
        ),
    ]
