# Generated by Django 5.1.14 on 2025-11-20 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PaymentReceived', '0004_alter_paymentreceived_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkImportPaymentReceived',
            fields=[
            ],
            options={
                'verbose_name': 'Bulk Import',
                'verbose_name_plural': 'Bulk Import',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('PaymentReceived.paymentreceived',),
        ),
    ]
