from django.shortcuts import render, get_object_or_404
from django.contrib import messages
from django.http import JsonResponse
from django.views.decorators.http import require_http_methods
from django.views.decorators.csrf import csrf_exempt
from django.urls import reverse
from wagtail import hooks  # Corrected import
from .models import Lift, FloorID, Brand, LiftType, MachineType, MachineBrand, DoorType, DoorBrand, ControllerBrand, Cabin
import json


def add_lift_custom(request):
    """Custom view for adding a lift"""
    if request.method == 'POST':
        try:
            data = json.loads(request.body)

            # Validate required fields
            required_fields = ['name', 'price', 'model', 'no_of_passengers', 'speed', 'brand', 'lift_type', 'machine_type', 'door_type']
            for field in required_fields:
                if not data.get(field):
                    return JsonResponse({
                        'success': False,
                        'error': f'{field.replace("_", " ").title()} is required'
                    }, status=400)

            # Get foreign key objects
            floor_id = None
            if data.get('floor_id'):
                floor_id = FloorID.objects.filter(id=data['floor_id']).first()

            brand = None
            if data.get('brand'):
                brand = Brand.objects.filter(id=data['brand']).first()

            lift_type = None
            if data.get('lift_type'):
                lift_type = LiftType.objects.filter(id=data['lift_type']).first()

            machine_type = None
            if data.get('machine_type'):
                machine_type = MachineType.objects.filter(id=data['machine_type']).first()

            machine_brand = None
            if data.get('machine_brand'):
                machine_brand = MachineBrand.objects.filter(id=data['machine_brand']).first()

            door_type = None
            if data.get('door_type'):
                door_type = DoorType.objects.filter(id=data['door_type']).first()

            door_brand = None
            if data.get('door_brand'):
                door_brand = DoorBrand.objects.filter(id=data['door_brand']).first()

            controller_brand = None
            if data.get('controller_brand'):
                controller_brand = ControllerBrand.objects.filter(id=data['controller_brand']).first()

            cabin = None
            if data.get('cabin'):
                cabin = Cabin.objects.filter(id=data['cabin']).first()

            # Parse no_of_passengers and calculate load_kg
            no_of_passengers = int(data.get('no_of_passengers', 0))
            load_kg = no_of_passengers * 68

            # Parse price
            price = float(data.get('price', 0))

            # Get required lift_code (manual entry)
            lift_code = data.get('lift_code', '').strip() if data.get('lift_code') else None

            # Validate lift_code is provided
            if not lift_code:
                return JsonResponse({
                    'success': False,
                    'error': 'Lift code is required.'
                }, status=400)

            # Validate lift_code uniqueness
            if Lift.objects.filter(lift_code=lift_code).exists():
                return JsonResponse({
                    'success': False,
                    'error': 'Lift code already exists. Please choose a different code.'
                }, status=400)

            # Create lift - reference_id will be auto-generated by the model
            lift = Lift.objects.create(
                lift_code=lift_code,  # Required field
                name=data['name'],
                price=price,
                model=data['model'],
                no_of_passengers=no_of_passengers,
                load_kg=load_kg,
                speed=data['speed'],
                floor_id=floor_id,
                brand=brand,
                lift_type=lift_type,
                machine_type=machine_type,
                machine_brand=machine_brand,
                door_type=door_type,
                door_brand=door_brand,
                controller_brand=controller_brand,
                cabin=cabin,
                block=data.get('block', ''),
                license_no=data.get('license_no'),
                license_start_date=data.get('license_start_date') if data.get('license_start_date') else None,
                license_end_date=data.get('license_end_date') if data.get('license_end_date') else None,
            )

            return JsonResponse({
                'success': True,
                'message': 'Lift created successfully',
                'lift': {
                    'reference_id': lift.reference_id,
                    'lift_code': lift.lift_code,
                    'name': lift.name,
                    'model': lift.model
                }
            })

        except Exception as e:
            return JsonResponse({
                'success': False,
                'error': str(e)
            }, status=500)

    # GET request - render form
    context = {
        'is_edit': False,
        'states': [],
        'routes': [],
        'branches': [],
    }
    return render(request, 'lift/add_lift_custom.html', context)


def edit_lift_custom(request, lift_code):
    """Custom view for editing a lift"""
    # Try to find lift by lift_code first, then by reference_id
    lift = None
    try:
        lift = Lift.objects.get(lift_code=lift_code)
    except Lift.DoesNotExist:
        try:
            lift = Lift.objects.get(reference_id=lift_code)
        except Lift.DoesNotExist:
            from django.http import Http404
            raise Http404("Lift not found")

    if request.method == 'POST':
        try:
            data = json.loads(request.body)

            # Update basic fields
            lift.name = data.get('name', lift.name)
            lift.price = float(data.get('price', lift.price))
            lift.model = data.get('model', lift.model)
            lift.no_of_passengers = int(data.get('no_of_passengers', lift.no_of_passengers))
            lift.load_kg = lift.no_of_passengers * 68
            lift.speed = data.get('speed', lift.speed)

            # Update lift_code (required field)
            new_lift_code = data.get('lift_code', '').strip() if data.get('lift_code') else None
            
            # Validate lift_code is provided
            if not new_lift_code:
                return JsonResponse({
                    'success': False,
                    'error': 'Lift code is required.'
                }, status=400)
            
            if new_lift_code != lift.lift_code:
                # Check if new lift_code already exists (excluding current lift)
                if Lift.objects.filter(lift_code=new_lift_code).exclude(id=lift.id).exists():
                    return JsonResponse({
                        'success': False,
                        'error': 'Lift code already exists. Please choose a different code.'
                    }, status=400)
                lift.lift_code = new_lift_code

            # Update foreign keys
            if data.get('floor_id'):
                lift.floor_id = FloorID.objects.filter(id=data['floor_id']).first()
            else:
                lift.floor_id = None

            if data.get('brand'):
                lift.brand = Brand.objects.filter(id=data['brand']).first()

            if data.get('lift_type'):
                lift.lift_type = LiftType.objects.filter(id=data['lift_type']).first()

            if data.get('machine_type'):
                lift.machine_type = MachineType.objects.filter(id=data['machine_type']).first()

            if data.get('machine_brand'):
                lift.machine_brand = MachineBrand.objects.filter(id=data['machine_brand']).first()
            else:
                lift.machine_brand = None

            if data.get('door_type'):
                lift.door_type = DoorType.objects.filter(id=data['door_type']).first()

            if data.get('door_brand'):
                lift.door_brand = DoorBrand.objects.filter(id=data['door_brand']).first()
            else:
                lift.door_brand = None

            if data.get('controller_brand'):
                lift.controller_brand = ControllerBrand.objects.filter(id=data['controller_brand']).first()
            else:
                lift.controller_brand = None

            if data.get('cabin'):
                lift.cabin = Cabin.objects.filter(id=data['cabin']).first()
            else:
                lift.cabin = None

            lift.block = data.get('block', lift.block)
            lift.license_no = data.get('license_no', lift.license_no)

            if data.get('license_start_date'):
                lift.license_start_date = data['license_start_date']
            if data.get('license_end_date'):
                lift.license_end_date = data['license_end_date']

            lift.save()

            return JsonResponse({
                'success': True,
                'message': 'Lift updated successfully'
            })

        except Exception as e:
            return JsonResponse({
                'success': False,
                'error': str(e)
            }, status=500)

    # GET request - render form with existing data
    context = {
        'is_edit': True,
        'lift': lift,
        'states': [],
        'routes': [],
        'branches': [],
    }
    return render(request, 'lift/add_lift_custom.html', context)


# Register custom URLs for Wagtail admin
@hooks.register('register_admin_urls')
def register_custom_lift_urls():
    from django.urls import path
    return [
        path('lift/add-custom/', add_lift_custom, name='add_lift_custom'),
        path('lift/edit-custom/<str:lift_code>/', edit_lift_custom, name='edit_lift_custom'),
    ]
