# Generated by Django 5.2.7 on 2025-10-20 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('item', models.CharField(max_length=200)),
                ('brand', models.CharField(blank=True, max_length=200)),
                ('file', models.CharField(max_length=200)),
                ('added_by', models.CharField(max_length=200)),
                ('requested_by', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
