# Generated by Django 5.2.3 on 2025-11-03 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Material_Request", "0001_initial"),
        ("items", "0004_item_purchase_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="materialrequest",
            name="item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="items.item"
            ),
        ),
    ]
