# Generated by Django 5.2.7 on 2025-11-07 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Material_Request', '0002_alter_materialrequest_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materialrequest',
            name='file',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
