# Generated by Django 5.1.14 on 2025-11-20 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Material_Request', '0003_alter_materialrequest_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulkImportMaterialRequest',
            fields=[
            ],
            options={
                'verbose_name': 'Bulk Import',
                'verbose_name_plural': 'Bulk Import',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('Material_Request.materialrequest',),
        ),
    ]
