# Generated by Django 5.2.7 on 2025-11-07 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amc', '0005_amcexpiringlastmonth_amcexpiringnextmonth_and_more'),
        ('invoice', '0003_invoice_amc_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='amc_type',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.PROTECT, to='amc.amctype'),
            preserve_default=False,
        ),
    ]
