# Generated by Django 5.1.14 on 2025-12-17 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0005_bulkimportinvoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('paid', 'Paid'), ('partially_paid', 'Partially Paid'), ('due', 'Due')], default='open', max_length=20),
        ),
    ]
