# Generated by Django 5.1.14 on 2026-01-07 04:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0006_add_due_status_to_invoice'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_date', models.DateTimeField(auto_now_add=True)),
                ('reminder_type', models.CharField(choices=[('due_soon', 'Due Soon (3 days before)'), ('due_today', 'Due Today'), ('overdue', 'Overdue')], default='overdue', max_length=20)),
                ('sent_to_email', models.EmailField(max_length=254)),
                ('sent_successfully', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='invoice.invoice')),
            ],
            options={
                'verbose_name': 'Invoice Reminder',
                'verbose_name_plural': 'Invoice Reminders',
                'ordering': ['-reminder_date'],
            },
        ),
    ]
