# Generated by Django 5.2.7 on 2025-11-04 10:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_time', models.DateTimeField(blank=True, null=True, verbose_name='Check-In Time')),
                ('check_in_date', models.DateField(blank=True, null=True, verbose_name='Check-In Date')),
                ('check_in_selfie', models.ImageField(blank=True, null=True, upload_to='attendance/selfies/', verbose_name='Check-In Selfie')),
                ('check_in_location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Check-In Location')),
                ('check_in_note', models.TextField(blank=True, null=True, verbose_name='Check-In Note')),
                ('check_out_time', models.DateTimeField(blank=True, null=True, verbose_name='Check-Out Time')),
                ('check_out_date', models.DateField(blank=True, null=True, verbose_name='Check-Out Date')),
                ('check_out_location', models.CharField(blank=True, max_length=255, null=True, verbose_name='Check-Out Location')),
                ('check_out_note', models.TextField(blank=True, null=True, verbose_name='Check-Out Note')),
                ('is_checked_in', models.BooleanField(default=False, verbose_name='Is Checked In')),
                ('is_checked_out', models.BooleanField(default=False, verbose_name='Is Checked Out')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attendance Record',
                'verbose_name_plural': 'Attendance Records',
                'ordering': ['-check_in_date', '-check_in_time'],
                'unique_together': {('user', 'check_in_date')},
            },
        ),
    ]
